// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCZH8fdNvmTf9Cx04POoW-ZhExt3ZDiS4E',
    appId: '1:62869792779:web:14b931226923f53aeaff0e',
    messagingSenderId: '62869792779',
    projectId: 'kirby-port',
    authDomain: 'kirby-port.firebaseapp.com',
    storageBucket: 'kirby-port.firebasestorage.app',
    measurementId: 'G-DTYQFVQEFQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAw5MKUIbnq4UswGuoVHeWO0GXBbZCGln0',
    appId: '1:62869792779:android:79581498938edc9deaff0e',
    messagingSenderId: '62869792779',
    projectId: 'kirby-port',
    storageBucket: 'kirby-port.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCRmt_ib67cl3T36_vrMLZZbIx4uVxe6pc',
    appId: '1:62869792779:ios:32cd189d4e88ee69eaff0e',
    messagingSenderId: '62869792779',
    projectId: 'kirby-port',
    storageBucket: 'kirby-port.firebasestorage.app',
    iosBundleId: 'com.example.kirbyPortApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCRmt_ib67cl3T36_vrMLZZbIx4uVxe6pc',
    appId: '1:62869792779:ios:32cd189d4e88ee69eaff0e',
    messagingSenderId: '62869792779',
    projectId: 'kirby-port',
    storageBucket: 'kirby-port.firebasestorage.app',
    iosBundleId: 'com.example.kirbyPortApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCZH8fdNvmTf9Cx04POoW-ZhExt3ZDiS4E',
    appId: '1:62869792779:web:00297b19797e0ed6eaff0e',
    messagingSenderId: '62869792779',
    projectId: 'kirby-port',
    authDomain: 'kirby-port.firebaseapp.com',
    storageBucket: 'kirby-port.firebasestorage.app',
    measurementId: 'G-PJ2KKNPP7C',
  );
}
